name: "Release"

on:
  push:
    paths:
      - "projects/ngx-rest/**"
    branches: [ "main" ]
  pull_request:
    paths:
      - "projects/ngx-rest/**"
    branches: [ "main" ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Dependencies
        uses: bahmutov/npm-install@v1
      - run: npm test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
