name: "Release"

on:
  push:
    paths:
      - "projects/ngx-rest/**"
    branches: [ "main" ]
  pull_request:
    paths:
      - "projects/ngx-rest/**"
    branches: [ "main" ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Dependencies
        uses: bahmutov/npm-install@v1
      - run: npm test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

  release:
    name: Release
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Dependencies
        uses: bahmutov/npm-install@v1
      - name: Build
        run: npm run build
      - name: Publish to npm and GitHub
        run: npx semantic-release@17
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
